### ISSUE TITLE
error writing an empty Radial file

### ISSUE THREAD

**Issue by neaptide** [rucool/hfradarpy#26]
I can read in a radial file that has no radials but cannot output an empty radial file using hfradarpy.Radials.to_ruv().  An empty radial file as the header metadata but no radials in an LLUV Table (see attached file -- 
[RDLi_HATY_2020_10_08_2100.txt](https://github.com/rucool/hfradarpy/files/9292603/RDLi_HATY_2020_10_08_2100.txt)) and the Table looks like this. 

%TableType: LLUV RDL3
%TableStart:
%% 
%% 
%TableEnd:
%%

I might be doing something wrong in qccodar do_merge(), but by reporting  the issue here I hope that you might know how to address it.   I'll be looking at it too since it is holding up reprocessing at UNC.

**BOLD** where the error occurs

Unexpected error in formatting one of these columns: LOND LATD ESPC ETMP BEAR HEAD
Traceback (most recent call last):
  File "/Users/codar/miniconda3/envs/qccodar/bin/qccodar", line 8, in <module>
    sys.exit(main())
  File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/qccodar/app.py", line 225, in main
    manual(datadir, pattern,configfile)
  File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/qccodar/app.py", line 86, in manual
    ofn = do_merge(datadir, fn, pattern, qccodar_values)
  File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/qccodar/codarutils.py", line 562, in do_merge
    write_output(r, ofn)
  File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/qccodar/codarutils.py", line 23, in **write_output**
    r.to_ruv(ofn, validate=False, overwrite=True)
  **File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/hfradarpy/radials.py", line 1163, in to_ruv
    self.data.columns = self._tables[1]["_TableHeader"][0]**
  File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/pandas/core/generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/pandas/core/generic.py", line 766, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/Users/codar/miniconda3/envs/qccodar/lib/python3.7/site-packages/pandas/core/internals/base.py", line 58, in _validate_set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
**ValueError: Length mismatch: Expected axis has 0 elements, new values have 1 elements**

**Comment by neaptide** [comment]
This seems to be happening when I read an empty radial file saved by LLUVMerger.   The attached file above is such an output.  It was created by merging 5 RadialShorts that did not have any radial data.  So it is **not** an empty radial table that hfradarpy.Radial class generated.  Also, I checked that it was not LLUVMerger error as older LLUVMerger versions save (almost) the same file formated as the one attached with exception of a few metadata lines being different.

**Comment by neaptide** [comment]
There is a work around now, but not sure it is just our own edge case or if it might come up somewhere.  Since we can read in the file and generate a Radial object (r), but the r._table[1] is

# an empty radial file by LLUVMerger 
ifn = './test_empty_Radials_qcd/RDLi_HATY_2020_10_08_2100.ruv'
r = read_lluv_file(ifn)

# In[]: r.data
# Out[]: 
# Empty DataFrame
# Columns: []
# Index: []

# and the table info is very empty for r._tables[1]
# In []: r._tables[1]
# Out[]: 
# OrderedDict([('TableType', 'LLUV RDL3'),
#              ('_TableHeader', [[''], ['']]),
#              ('TableStart', ''),
#              ('data',
#               Empty DataFrame
#               Columns: []
#               Index: [])])

I create an other empty Radial object based on a good template and inject the properly formed table and dataframe into the radial object above since it too is empty of radials.

# create an empty Radial class object with LLUVMerger type output -- using example that has data above
formatfile = './test_empty_Radials_qcd/RDLi_HATY_2020_10_08_2000.ruv'
re = Radial(formatfile,empty_radial=True)

# In []: re.data
# Out[]: 
# Empty DataFrame
# Columns: [LOND, LATD, VELU, VELV, VFLG, ESPC, ETMP, EDEV, MAXV, MINV, EDVC, ERSC, ERTC, XDST, YDST, RNGE, BEAR, VELO, HEAD, SPRC]
# Index: []

# copy correctly formatted empty data table in re (Radial object) to r (Radial object)
r._tables[1] = re._tables[1]
r.data = re._tables[1]['data']
